#ifndef DCAL_READER_H
#define DCAL_READER_H

/* Generated by flatcc 0.3.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef alignas
#include <stdalign.h>
#endif
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct DCAL_session_Handshake_table *DCAL_session_Handshake_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Handshake_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Handshake_mutable_vec_t;
typedef const struct DCAL_session_Event_table *DCAL_session_Event_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Event_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Event_mutable_vec_t;
typedef const struct DCAL_session_U32_table *DCAL_session_U32_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_U32_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_U32_mutable_vec_t;
typedef const struct DCAL_session_String_table *DCAL_session_String_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_String_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_String_mutable_vec_t;
typedef const struct DCAL_session_Status_table *DCAL_session_Status_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Status_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Status_mutable_vec_t;
typedef const struct DCAL_session_Version_table *DCAL_session_Version_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Version_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Version_mutable_vec_t;
typedef const struct DCAL_session_Globals_table *DCAL_session_Globals_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Globals_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Globals_mutable_vec_t;
typedef const struct DCAL_session_Profile_table *DCAL_session_Profile_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Profile_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Profile_mutable_vec_t;
typedef const struct DCAL_session_P_entry_table *DCAL_session_P_entry_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_P_entry_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_P_entry_mutable_vec_t;
typedef const struct DCAL_session_Profile_list_table *DCAL_session_Profile_list_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Profile_list_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Profile_list_mutable_vec_t;
typedef const struct DCAL_session_Scan_item_table *DCAL_session_Scan_item_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Scan_item_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Scan_item_mutable_vec_t;
typedef const struct DCAL_session_Scan_list_table *DCAL_session_Scan_list_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Scan_list_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Scan_list_mutable_vec_t;
typedef const struct DCAL_session_Time_table *DCAL_session_Time_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Time_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Time_mutable_vec_t;
typedef const struct DCAL_session_Filexfer_table *DCAL_session_Filexfer_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Filexfer_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Filexfer_mutable_vec_t;
typedef const struct DCAL_session_Command_table *DCAL_session_Command_table_t;
typedef const flatbuffers_uoffset_t *DCAL_session_Command_vec_t;
typedef flatbuffers_uoffset_t *DCAL_session_Command_mutable_vec_t;

typedef uint32_t DCAL_session_Magic_enum_t;
__flatbuffers_define_integer_type(DCAL_session_Magic, DCAL_session_Magic_enum_t, 32)
#define DCAL_session_Magic_INVALID ((DCAL_session_Magic_enum_t)0UL)
#define DCAL_session_Magic_HELLO ((DCAL_session_Magic_enum_t)123UL)
#define DCAL_session_Magic_NACK ((DCAL_session_Magic_enum_t)404UL)
#define DCAL_session_Magic_ACK ((DCAL_session_Magic_enum_t)555UL)

static inline const char *DCAL_session_Magic_name(DCAL_session_Magic_enum_t value)
{
    switch (value) {
    case DCAL_session_Magic_INVALID: return "INVALID";
    case DCAL_session_Magic_HELLO: return "HELLO";
    case DCAL_session_Magic_NACK: return "NACK";
    case DCAL_session_Magic_ACK: return "ACK";
    default: return "";
    }
}

typedef uint32_t DCAL_session_Commands_enum_t;
__flatbuffers_define_integer_type(DCAL_session_Commands, DCAL_session_Commands_enum_t, 32)
#define DCAL_session_Commands_INVALID ((DCAL_session_Commands_enum_t)0UL)
#define DCAL_session_Commands_GETVERSIONS ((DCAL_session_Commands_enum_t)1UL)
#define DCAL_session_Commands_GETSTATUS ((DCAL_session_Commands_enum_t)2UL)
#define DCAL_session_Commands_GETGLOBALS ((DCAL_session_Commands_enum_t)3UL)
#define DCAL_session_Commands_SETGLOBALS ((DCAL_session_Commands_enum_t)4UL)
#define DCAL_session_Commands_GETPROFILE ((DCAL_session_Commands_enum_t)5UL)
#define DCAL_session_Commands_SETPROFILE ((DCAL_session_Commands_enum_t)6UL)
#define DCAL_session_Commands_DELPROFILE ((DCAL_session_Commands_enum_t)7UL)
#define DCAL_session_Commands_GETPROFILELIST ((DCAL_session_Commands_enum_t)8UL)
#define DCAL_session_Commands_GETSCANLIST ((DCAL_session_Commands_enum_t)9UL)
#define DCAL_session_Commands_ACTIVATEPROFILE ((DCAL_session_Commands_enum_t)10UL)
#define DCAL_session_Commands_WIFIENABLE ((DCAL_session_Commands_enum_t)11UL)
#define DCAL_session_Commands_WIFIDISABLE ((DCAL_session_Commands_enum_t)12UL)
#define DCAL_session_Commands_WIFIRESTART ((DCAL_session_Commands_enum_t)13UL)
#define DCAL_session_Commands_SYSTEMREBOOT ((DCAL_session_Commands_enum_t)14UL)
#define DCAL_session_Commands_SETTIME ((DCAL_session_Commands_enum_t)15UL)
#define DCAL_session_Commands_GETTIME ((DCAL_session_Commands_enum_t)16UL)
#define DCAL_session_Commands_NTPDATE ((DCAL_session_Commands_enum_t)17UL)
#define DCAL_session_Commands_FILEPUSH ((DCAL_session_Commands_enum_t)18UL)
#define DCAL_session_Commands_FILEPULL ((DCAL_session_Commands_enum_t)19UL)
#define DCAL_session_Commands_FWUPDATE ((DCAL_session_Commands_enum_t)20UL)
#define DCAL_session_Commands_CLIFILE ((DCAL_session_Commands_enum_t)21UL)
#define DCAL_session_Commands_GETLOGS ((DCAL_session_Commands_enum_t)22UL)

static inline const char *DCAL_session_Commands_name(DCAL_session_Commands_enum_t value)
{
    switch (value) {
    case DCAL_session_Commands_INVALID: return "INVALID";
    case DCAL_session_Commands_GETVERSIONS: return "GETVERSIONS";
    case DCAL_session_Commands_GETSTATUS: return "GETSTATUS";
    case DCAL_session_Commands_GETGLOBALS: return "GETGLOBALS";
    case DCAL_session_Commands_SETGLOBALS: return "SETGLOBALS";
    case DCAL_session_Commands_GETPROFILE: return "GETPROFILE";
    case DCAL_session_Commands_SETPROFILE: return "SETPROFILE";
    case DCAL_session_Commands_DELPROFILE: return "DELPROFILE";
    case DCAL_session_Commands_GETPROFILELIST: return "GETPROFILELIST";
    case DCAL_session_Commands_GETSCANLIST: return "GETSCANLIST";
    case DCAL_session_Commands_ACTIVATEPROFILE: return "ACTIVATEPROFILE";
    case DCAL_session_Commands_WIFIENABLE: return "WIFIENABLE";
    case DCAL_session_Commands_WIFIDISABLE: return "WIFIDISABLE";
    case DCAL_session_Commands_WIFIRESTART: return "WIFIRESTART";
    case DCAL_session_Commands_SYSTEMREBOOT: return "SYSTEMREBOOT";
    case DCAL_session_Commands_SETTIME: return "SETTIME";
    case DCAL_session_Commands_GETTIME: return "GETTIME";
    case DCAL_session_Commands_NTPDATE: return "NTPDATE";
    case DCAL_session_Commands_FILEPUSH: return "FILEPUSH";
    case DCAL_session_Commands_FILEPULL: return "FILEPULL";
    case DCAL_session_Commands_FWUPDATE: return "FWUPDATE";
    case DCAL_session_Commands_CLIFILE: return "CLIFILE";
    case DCAL_session_Commands_GETLOGS: return "GETLOGS";
    default: return "";
    }
}



struct DCAL_session_Handshake_table { uint8_t unused__; };

#ifndef DCAL_session_Handshake_identifier
#define DCAL_session_Handshake_identifier flatbuffers_identifier
#endif
#define DCAL_session_Handshake_type_hash ((flatbuffers_thash_t)0xe7ee4310)
#define DCAL_session_Handshake_type_identifier "\x10\x43\xee\xe7"
static inline size_t DCAL_session_Handshake_vec_len(DCAL_session_Handshake_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Handshake_table_t DCAL_session_Handshake_vec_at(DCAL_session_Handshake_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Handshake_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Handshake)

static inline flatbuffers_bool_t DCAL_session_Handshake_server(DCAL_session_Handshake_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 0, 0, t)
static inline int DCAL_session_Handshake_server_is_present(DCAL_session_Handshake_table_t t)
__flatbuffers_field_present(0, t)

static inline DCAL_session_Magic_enum_t DCAL_session_Handshake_magic(DCAL_session_Handshake_table_t t)
__flatbuffers_scalar_field(DCAL_session_Magic, 1, 0, t)
static inline int DCAL_session_Handshake_magic_is_present(DCAL_session_Handshake_table_t t)
__flatbuffers_field_present(1, t)

static inline flatbuffers_string_t DCAL_session_Handshake_ip(DCAL_session_Handshake_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 2, t, 0)
static inline int DCAL_session_Handshake_ip_is_present(DCAL_session_Handshake_table_t t)
__flatbuffers_field_present(2, t)

static inline uint32_t DCAL_session_Handshake_api_level(DCAL_session_Handshake_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 3, 0, t)
static inline int DCAL_session_Handshake_api_level_is_present(DCAL_session_Handshake_table_t t)
__flatbuffers_field_present(3, t)

static inline uint32_t DCAL_session_Handshake_error(DCAL_session_Handshake_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 4, 0, t)
static inline int DCAL_session_Handshake_error_is_present(DCAL_session_Handshake_table_t t)
__flatbuffers_field_present(4, t)


struct DCAL_session_Event_table { uint8_t unused__; };

#ifndef DCAL_session_Event_identifier
#define DCAL_session_Event_identifier flatbuffers_identifier
#endif
#define DCAL_session_Event_type_hash ((flatbuffers_thash_t)0x5b8cb5d)
#define DCAL_session_Event_type_identifier "\x5d\xcb\xb8\x05"
static inline size_t DCAL_session_Event_vec_len(DCAL_session_Event_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Event_table_t DCAL_session_Event_vec_at(DCAL_session_Event_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Event_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Event)

static inline uint32_t DCAL_session_Event_e_type(DCAL_session_Event_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 0, 0, t)
static inline int DCAL_session_Event_e_type_is_present(DCAL_session_Event_table_t t)
__flatbuffers_field_present(0, t)

static inline uint32_t DCAL_session_Event_status(DCAL_session_Event_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 1, 0, t)
static inline int DCAL_session_Event_status_is_present(DCAL_session_Event_table_t t)
__flatbuffers_field_present(1, t)

static inline uint32_t DCAL_session_Event_reason(DCAL_session_Event_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 2, 0, t)
static inline int DCAL_session_Event_reason_is_present(DCAL_session_Event_table_t t)
__flatbuffers_field_present(2, t)

static inline flatbuffers_string_t DCAL_session_Event_eth_addr(DCAL_session_Event_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 3, t, 0)
static inline int DCAL_session_Event_eth_addr_is_present(DCAL_session_Event_table_t t)
__flatbuffers_field_present(3, t)

static inline uint16_t DCAL_session_Event_flags(DCAL_session_Event_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint16, 4, 0, t)
static inline int DCAL_session_Event_flags_is_present(DCAL_session_Event_table_t t)
__flatbuffers_field_present(4, t)


struct DCAL_session_U32_table { uint8_t unused__; };

#ifndef DCAL_session_U32_identifier
#define DCAL_session_U32_identifier flatbuffers_identifier
#endif
#define DCAL_session_U32_type_hash ((flatbuffers_thash_t)0xdc0a1f1f)
#define DCAL_session_U32_type_identifier "\x1f\x1f\x0a\xdc"
static inline size_t DCAL_session_U32_vec_len(DCAL_session_U32_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_U32_table_t DCAL_session_U32_vec_at(DCAL_session_U32_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_U32_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_U32)

static inline uint32_t DCAL_session_U32_value(DCAL_session_U32_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 0, 0, t)
static inline int DCAL_session_U32_value_is_present(DCAL_session_U32_table_t t)
__flatbuffers_field_present(0, t)


struct DCAL_session_String_table { uint8_t unused__; };

#ifndef DCAL_session_String_identifier
#define DCAL_session_String_identifier flatbuffers_identifier
#endif
#define DCAL_session_String_type_hash ((flatbuffers_thash_t)0x67907baa)
#define DCAL_session_String_type_identifier "\xaa\x7b\x90\x67"
static inline size_t DCAL_session_String_vec_len(DCAL_session_String_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_String_table_t DCAL_session_String_vec_at(DCAL_session_String_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_String_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_String)

static inline flatbuffers_string_t DCAL_session_String_value(DCAL_session_String_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 0, t, 0)
static inline int DCAL_session_String_value_is_present(DCAL_session_String_table_t t)
__flatbuffers_field_present(0, t)


struct DCAL_session_Status_table { uint8_t unused__; };

#ifndef DCAL_session_Status_identifier
#define DCAL_session_Status_identifier flatbuffers_identifier
#endif
#define DCAL_session_Status_type_hash ((flatbuffers_thash_t)0xa5becae9)
#define DCAL_session_Status_type_identifier "\xe9\xca\xbe\xa5"
static inline size_t DCAL_session_Status_vec_len(DCAL_session_Status_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Status_table_t DCAL_session_Status_vec_at(DCAL_session_Status_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Status_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Status)

static inline uint32_t DCAL_session_Status_cardState(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 0, 0, t)
static inline int DCAL_session_Status_cardState_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(0, t)

static inline flatbuffers_string_t DCAL_session_Status_ProfileName(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 1, t, 0)
static inline int DCAL_session_Status_ProfileName_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(1, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Status_ssid(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 2, t, 0)
static inline int DCAL_session_Status_ssid_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(2, t)

static inline uint32_t DCAL_session_Status_channel(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 3, 0, t)
static inline int DCAL_session_Status_channel_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(3, t)

static inline int32_t DCAL_session_Status_rssi(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_int32, 4, 0, t)
static inline int DCAL_session_Status_rssi_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(4, t)

static inline flatbuffers_string_t DCAL_session_Status_clientName(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 5, t, 0)
static inline int DCAL_session_Status_clientName_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(5, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Status_mac(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 6, t, 0)
static inline int DCAL_session_Status_mac_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(6, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Status_ip(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 7, t, 0)
static inline int DCAL_session_Status_ip_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(7, t)

static inline flatbuffers_string_vec_t DCAL_session_Status_ipv6(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_string_vec_t, 8, t, 0)
static inline int DCAL_session_Status_ipv6_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(8, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Status_AP_mac(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 9, t, 0)
static inline int DCAL_session_Status_AP_mac_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(9, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Status_AP_ip(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 10, t, 0)
static inline int DCAL_session_Status_AP_ip_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(10, t)

static inline flatbuffers_string_t DCAL_session_Status_AP_name(DCAL_session_Status_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 11, t, 0)
static inline int DCAL_session_Status_AP_name_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(11, t)

static inline uint32_t DCAL_session_Status_bitRate(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 12, 0, t)
static inline int DCAL_session_Status_bitRate_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(12, t)

static inline uint32_t DCAL_session_Status_txPower(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 13, 0, t)
static inline int DCAL_session_Status_txPower_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(13, t)

static inline uint32_t DCAL_session_Status_dtim(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 14, 0, t)
static inline int DCAL_session_Status_dtim_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(14, t)

static inline uint32_t DCAL_session_Status_beaconPeriod(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 15, 0, t)
static inline int DCAL_session_Status_beaconPeriod_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(15, t)

static inline uint32_t DCAL_session_Status_numipv6addrs(DCAL_session_Status_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 16, 0, t)
static inline int DCAL_session_Status_numipv6addrs_is_present(DCAL_session_Status_table_t t)
__flatbuffers_field_present(16, t)


struct DCAL_session_Version_table { uint8_t unused__; };

#ifndef DCAL_session_Version_identifier
#define DCAL_session_Version_identifier flatbuffers_identifier
#endif
#define DCAL_session_Version_type_hash ((flatbuffers_thash_t)0x23ca9341)
#define DCAL_session_Version_type_identifier "\x41\x93\xca\x23"
static inline size_t DCAL_session_Version_vec_len(DCAL_session_Version_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Version_table_t DCAL_session_Version_vec_at(DCAL_session_Version_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Version_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Version)

static inline uint32_t DCAL_session_Version_sdk(DCAL_session_Version_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 0, 0, t)
static inline int DCAL_session_Version_sdk_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(0, t)

static inline uint32_t DCAL_session_Version_chipset(DCAL_session_Version_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 1, 0, t)
static inline int DCAL_session_Version_chipset_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(1, t)

static inline uint32_t DCAL_session_Version_sys(DCAL_session_Version_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 2, 0, t)
static inline int DCAL_session_Version_sys_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(2, t)

static inline uint32_t DCAL_session_Version_driver(DCAL_session_Version_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 3, 0, t)
static inline int DCAL_session_Version_driver_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(3, t)

static inline flatbuffers_string_t DCAL_session_Version_firmware(DCAL_session_Version_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 4, t, 0)
static inline int DCAL_session_Version_firmware_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(4, t)

static inline flatbuffers_string_t DCAL_session_Version_supplicant(DCAL_session_Version_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 5, t, 0)
static inline int DCAL_session_Version_supplicant_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(5, t)

static inline flatbuffers_string_t DCAL_session_Version_release(DCAL_session_Version_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 6, t, 0)
static inline int DCAL_session_Version_release_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(6, t)

static inline uint32_t DCAL_session_Version_dcas(DCAL_session_Version_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 7, 0, t)
static inline int DCAL_session_Version_dcas_is_present(DCAL_session_Version_table_t t)
__flatbuffers_field_present(7, t)


struct DCAL_session_Globals_table { uint8_t unused__; };

#ifndef DCAL_session_Globals_identifier
#define DCAL_session_Globals_identifier flatbuffers_identifier
#endif
#define DCAL_session_Globals_type_hash ((flatbuffers_thash_t)0x992f90f5)
#define DCAL_session_Globals_type_identifier "\xf5\x90\x2f\x99"
static inline size_t DCAL_session_Globals_vec_len(DCAL_session_Globals_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Globals_table_t DCAL_session_Globals_vec_at(DCAL_session_Globals_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Globals_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Globals)

static inline uint32_t DCAL_session_Globals_auth(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 0, 0, t)
static inline int DCAL_session_Globals_auth_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(0, t)

static inline uint32_t DCAL_session_Globals_channel_set_a(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 1, 0, t)
static inline int DCAL_session_Globals_channel_set_a_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(1, t)

static inline uint32_t DCAL_session_Globals_channel_set_b(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 2, 0, t)
static inline int DCAL_session_Globals_channel_set_b_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(2, t)

static inline flatbuffers_bool_t DCAL_session_Globals_auto_profile(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 3, 0, t)
static inline int DCAL_session_Globals_auto_profile_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(3, t)

static inline uint32_t DCAL_session_Globals_beacon_miss(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 4, 0, t)
static inline int DCAL_session_Globals_beacon_miss_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(4, t)

static inline flatbuffers_bool_t DCAL_session_Globals_bt_coex(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 5, 0, t)
static inline int DCAL_session_Globals_bt_coex_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(5, t)

static inline flatbuffers_bool_t DCAL_session_Globals_ccx(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 6, 0, t)
static inline int DCAL_session_Globals_ccx_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(6, t)

static inline flatbuffers_string_t DCAL_session_Globals_cert_path(DCAL_session_Globals_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 7, t, 0)
static inline int DCAL_session_Globals_cert_path_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(7, t)

static inline flatbuffers_bool_t DCAL_session_Globals_date_check(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 8, 0, t)
static inline int DCAL_session_Globals_date_check_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(8, t)

static inline uint32_t DCAL_session_Globals_def_adhoc(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 9, 0, t)
static inline int DCAL_session_Globals_def_adhoc_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(9, t)

static inline flatbuffers_bool_t DCAL_session_Globals_fips(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 10, 0, t)
static inline int DCAL_session_Globals_fips_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(10, t)

static inline uint32_t DCAL_session_Globals_pmk(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 11, 0, t)
static inline int DCAL_session_Globals_pmk_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(11, t)

static inline uint32_t DCAL_session_Globals_probe_delay(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 12, 0, t)
static inline int DCAL_session_Globals_probe_delay_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(12, t)

static inline uint32_t DCAL_session_Globals_regdomain(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 13, 0, t)
static inline int DCAL_session_Globals_regdomain_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(13, t)

static inline uint32_t DCAL_session_Globals_roam_period(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 14, 0, t)
static inline int DCAL_session_Globals_roam_period_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(14, t)

static inline uint32_t DCAL_session_Globals_roam_periodms(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 15, 0, t)
static inline int DCAL_session_Globals_roam_periodms_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(15, t)

static inline uint32_t DCAL_session_Globals_roam_trigger(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 16, 0, t)
static inline int DCAL_session_Globals_roam_trigger_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(16, t)

static inline uint32_t DCAL_session_Globals_rts(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 17, 0, t)
static inline int DCAL_session_Globals_rts_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(17, t)

static inline uint32_t DCAL_session_Globals_scan_dfs(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 18, 0, t)
static inline int DCAL_session_Globals_scan_dfs_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(18, t)

static inline uint32_t DCAL_session_Globals_ttls(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 19, 0, t)
static inline int DCAL_session_Globals_ttls_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(19, t)

static inline flatbuffers_bool_t DCAL_session_Globals_uapsd(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 20, 0, t)
static inline int DCAL_session_Globals_uapsd_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(20, t)

static inline flatbuffers_bool_t DCAL_session_Globals_wmm(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 21, 0, t)
static inline int DCAL_session_Globals_wmm_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(21, t)

static inline flatbuffers_bool_t DCAL_session_Globals_ignore_null_ssid(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 22, 0, t)
static inline int DCAL_session_Globals_ignore_null_ssid_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(22, t)

static inline uint32_t DCAL_session_Globals_dfs_channels(DCAL_session_Globals_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 23, 0, t)
static inline int DCAL_session_Globals_dfs_channels_is_present(DCAL_session_Globals_table_t t)
__flatbuffers_field_present(23, t)


struct DCAL_session_Profile_table { uint8_t unused__; };

#ifndef DCAL_session_Profile_identifier
#define DCAL_session_Profile_identifier flatbuffers_identifier
#endif
#define DCAL_session_Profile_type_hash ((flatbuffers_thash_t)0x2dcf2330)
#define DCAL_session_Profile_type_identifier "\x30\x23\xcf\x2d"
static inline size_t DCAL_session_Profile_vec_len(DCAL_session_Profile_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Profile_table_t DCAL_session_Profile_vec_at(DCAL_session_Profile_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Profile_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Profile)

static inline flatbuffers_string_t DCAL_session_Profile_name(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 0, t, 0)
static inline int DCAL_session_Profile_name_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(0, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Profile_ssid(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 1, t, 0)
static inline int DCAL_session_Profile_ssid_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(1, t)

static inline flatbuffers_string_t DCAL_session_Profile_client_name(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 2, t, 0)
static inline int DCAL_session_Profile_client_name_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(2, t)

static inline uint32_t DCAL_session_Profile_txPwr(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 3, 0, t)
static inline int DCAL_session_Profile_txPwr_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(3, t)

static inline uint32_t DCAL_session_Profile_pwrsave(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 4, 0, t)
static inline int DCAL_session_Profile_pwrsave_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(4, t)

static inline uint32_t DCAL_session_Profile_pspDelay(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 5, 0, t)
static inline int DCAL_session_Profile_pspDelay_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(5, t)

static inline uint32_t DCAL_session_Profile_weptype(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 6, 0, t)
static inline int DCAL_session_Profile_weptype_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(6, t)

static inline uint32_t DCAL_session_Profile_auth(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 7, 0, t)
static inline int DCAL_session_Profile_auth_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(7, t)

static inline uint32_t DCAL_session_Profile_eap(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 8, 0, t)
static inline int DCAL_session_Profile_eap_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(8, t)

static inline uint32_t DCAL_session_Profile_bitrate(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 9, 0, t)
static inline int DCAL_session_Profile_bitrate_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(9, t)

static inline uint32_t DCAL_session_Profile_radiomode(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 10, 0, t)
static inline int DCAL_session_Profile_radiomode_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(10, t)

static inline flatbuffers_string_t DCAL_session_Profile_security1(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 11, t, 0)
static inline int DCAL_session_Profile_security1_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(11, t)

static inline flatbuffers_string_t DCAL_session_Profile_security2(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 12, t, 0)
static inline int DCAL_session_Profile_security2_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(12, t)

static inline flatbuffers_string_t DCAL_session_Profile_security3(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 13, t, 0)
static inline int DCAL_session_Profile_security3_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(13, t)

static inline flatbuffers_string_t DCAL_session_Profile_security4(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 14, t, 0)
static inline int DCAL_session_Profile_security4_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(14, t)

static inline flatbuffers_string_t DCAL_session_Profile_security5(DCAL_session_Profile_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 15, t, 0)
static inline int DCAL_session_Profile_security5_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(15, t)

static inline uint32_t DCAL_session_Profile_weptxkey(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 16, 0, t)
static inline int DCAL_session_Profile_weptxkey_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(16, t)

static inline flatbuffers_bool_t DCAL_session_Profile_autoprofile(DCAL_session_Profile_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 17, 0, t)
static inline int DCAL_session_Profile_autoprofile_is_present(DCAL_session_Profile_table_t t)
__flatbuffers_field_present(17, t)


struct DCAL_session_P_entry_table { uint8_t unused__; };

#ifndef DCAL_session_P_entry_identifier
#define DCAL_session_P_entry_identifier flatbuffers_identifier
#endif
#define DCAL_session_P_entry_type_hash ((flatbuffers_thash_t)0xf897aa7e)
#define DCAL_session_P_entry_type_identifier "\x7e\xaa\x97\xf8"
static inline size_t DCAL_session_P_entry_vec_len(DCAL_session_P_entry_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_P_entry_table_t DCAL_session_P_entry_vec_at(DCAL_session_P_entry_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_P_entry_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_P_entry)

static inline flatbuffers_string_t DCAL_session_P_entry_name(DCAL_session_P_entry_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 0, t, 0)
static inline int DCAL_session_P_entry_name_is_present(DCAL_session_P_entry_table_t t)
__flatbuffers_field_present(0, t)

static inline flatbuffers_bool_t DCAL_session_P_entry_active(DCAL_session_P_entry_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 1, 0, t)
static inline int DCAL_session_P_entry_active_is_present(DCAL_session_P_entry_table_t t)
__flatbuffers_field_present(1, t)

static inline flatbuffers_bool_t DCAL_session_P_entry_autoprof(DCAL_session_P_entry_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 2, 0, t)
static inline int DCAL_session_P_entry_autoprof_is_present(DCAL_session_P_entry_table_t t)
__flatbuffers_field_present(2, t)


struct DCAL_session_Profile_list_table { uint8_t unused__; };

#ifndef DCAL_session_Profile_list_identifier
#define DCAL_session_Profile_list_identifier flatbuffers_identifier
#endif
#define DCAL_session_Profile_list_type_hash ((flatbuffers_thash_t)0xe6d21719)
#define DCAL_session_Profile_list_type_identifier "\x19\x17\xd2\xe6"
static inline size_t DCAL_session_Profile_list_vec_len(DCAL_session_Profile_list_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Profile_list_table_t DCAL_session_Profile_list_vec_at(DCAL_session_Profile_list_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Profile_list_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Profile_list)

static inline DCAL_session_P_entry_vec_t DCAL_session_Profile_list_profiles(DCAL_session_Profile_list_table_t t)
__flatbuffers_vector_field(DCAL_session_P_entry_vec_t, 0, t, 0)
static inline int DCAL_session_Profile_list_profiles_is_present(DCAL_session_Profile_list_table_t t)
__flatbuffers_field_present(0, t)


struct DCAL_session_Scan_item_table { uint8_t unused__; };

#ifndef DCAL_session_Scan_item_identifier
#define DCAL_session_Scan_item_identifier flatbuffers_identifier
#endif
#define DCAL_session_Scan_item_type_hash ((flatbuffers_thash_t)0xeae08c5c)
#define DCAL_session_Scan_item_type_identifier "\x5c\x8c\xe0\xea"
static inline size_t DCAL_session_Scan_item_vec_len(DCAL_session_Scan_item_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Scan_item_table_t DCAL_session_Scan_item_vec_at(DCAL_session_Scan_item_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Scan_item_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Scan_item)

static inline uint8_t DCAL_session_Scan_item_channel(DCAL_session_Scan_item_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint8, 0, 0, t)
static inline int DCAL_session_Scan_item_channel_is_present(DCAL_session_Scan_item_table_t t)
__flatbuffers_field_present(0, t)

static inline int32_t DCAL_session_Scan_item_rssi(DCAL_session_Scan_item_table_t t)
__flatbuffers_scalar_field(flatbuffers_int32, 1, 0, t)
static inline int DCAL_session_Scan_item_rssi_is_present(DCAL_session_Scan_item_table_t t)
__flatbuffers_field_present(1, t)

static inline uint32_t DCAL_session_Scan_item_securityMask(DCAL_session_Scan_item_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 2, 0, t)
static inline int DCAL_session_Scan_item_securityMask_is_present(DCAL_session_Scan_item_table_t t)
__flatbuffers_field_present(2, t)

static inline flatbuffers_bool_t DCAL_session_Scan_item_bss(DCAL_session_Scan_item_table_t t)
__flatbuffers_scalar_field(flatbuffers_bool, 3, 0, t)
static inline int DCAL_session_Scan_item_bss_is_present(DCAL_session_Scan_item_table_t t)
__flatbuffers_field_present(3, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Scan_item_mac(DCAL_session_Scan_item_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 4, t, 0)
static inline int DCAL_session_Scan_item_mac_is_present(DCAL_session_Scan_item_table_t t)
__flatbuffers_field_present(4, t)

static inline flatbuffers_uint8_vec_t DCAL_session_Scan_item_ssid(DCAL_session_Scan_item_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 5, t, 0)
static inline int DCAL_session_Scan_item_ssid_is_present(DCAL_session_Scan_item_table_t t)
__flatbuffers_field_present(5, t)


struct DCAL_session_Scan_list_table { uint8_t unused__; };

#ifndef DCAL_session_Scan_list_identifier
#define DCAL_session_Scan_list_identifier flatbuffers_identifier
#endif
#define DCAL_session_Scan_list_type_hash ((flatbuffers_thash_t)0x2b693cc3)
#define DCAL_session_Scan_list_type_identifier "\xc3\x3c\x69\x2b"
static inline size_t DCAL_session_Scan_list_vec_len(DCAL_session_Scan_list_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Scan_list_table_t DCAL_session_Scan_list_vec_at(DCAL_session_Scan_list_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Scan_list_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Scan_list)

static inline DCAL_session_Scan_item_vec_t DCAL_session_Scan_list_items(DCAL_session_Scan_list_table_t t)
__flatbuffers_vector_field(DCAL_session_Scan_item_vec_t, 0, t, 0)
static inline int DCAL_session_Scan_list_items_is_present(DCAL_session_Scan_list_table_t t)
__flatbuffers_field_present(0, t)


struct DCAL_session_Time_table { uint8_t unused__; };

#ifndef DCAL_session_Time_identifier
#define DCAL_session_Time_identifier flatbuffers_identifier
#endif
#define DCAL_session_Time_type_hash ((flatbuffers_thash_t)0xce80618e)
#define DCAL_session_Time_type_identifier "\x8e\x61\x80\xce"
static inline size_t DCAL_session_Time_vec_len(DCAL_session_Time_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Time_table_t DCAL_session_Time_vec_at(DCAL_session_Time_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Time_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Time)

static inline int32_t DCAL_session_Time_tv_sec(DCAL_session_Time_table_t t)
__flatbuffers_scalar_field(flatbuffers_int32, 0, 0, t)
static inline int DCAL_session_Time_tv_sec_is_present(DCAL_session_Time_table_t t)
__flatbuffers_field_present(0, t)

static inline int32_t DCAL_session_Time_tv_usec(DCAL_session_Time_table_t t)
__flatbuffers_scalar_field(flatbuffers_int32, 1, 0, t)
static inline int DCAL_session_Time_tv_usec_is_present(DCAL_session_Time_table_t t)
__flatbuffers_field_present(1, t)


struct DCAL_session_Filexfer_table { uint8_t unused__; };

#ifndef DCAL_session_Filexfer_identifier
#define DCAL_session_Filexfer_identifier flatbuffers_identifier
#endif
#define DCAL_session_Filexfer_type_hash ((flatbuffers_thash_t)0xd295470c)
#define DCAL_session_Filexfer_type_identifier "\x0c\x47\x95\xd2"
static inline size_t DCAL_session_Filexfer_vec_len(DCAL_session_Filexfer_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Filexfer_table_t DCAL_session_Filexfer_vec_at(DCAL_session_Filexfer_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Filexfer_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Filexfer)

static inline flatbuffers_string_t DCAL_session_Filexfer_file_path(DCAL_session_Filexfer_table_t t)
__flatbuffers_vector_field(flatbuffers_string_t, 0, t, 0)
static inline int DCAL_session_Filexfer_file_path_is_present(DCAL_session_Filexfer_table_t t)
__flatbuffers_field_present(0, t)

static inline int32_t DCAL_session_Filexfer_size(DCAL_session_Filexfer_table_t t)
__flatbuffers_scalar_field(flatbuffers_int32, 1, 0, t)
static inline int DCAL_session_Filexfer_size_is_present(DCAL_session_Filexfer_table_t t)
__flatbuffers_field_present(1, t)

static inline int32_t DCAL_session_Filexfer_mode(DCAL_session_Filexfer_table_t t)
__flatbuffers_scalar_field(flatbuffers_int32, 2, 0, t)
static inline int DCAL_session_Filexfer_mode_is_present(DCAL_session_Filexfer_table_t t)
__flatbuffers_field_present(2, t)

typedef uint8_t DCAL_session_Cmd_pl_union_type_t;
__flatbuffers_define_integer_type(DCAL_session_Cmd_pl, DCAL_session_Cmd_pl_union_type_t, 8)
#define DCAL_session_Cmd_pl_NONE ((DCAL_session_Cmd_pl_union_type_t)0U)
#define DCAL_session_Cmd_pl_Globals ((DCAL_session_Cmd_pl_union_type_t)1U)
#define DCAL_session_Cmd_pl_Profile ((DCAL_session_Cmd_pl_union_type_t)2U)
#define DCAL_session_Cmd_pl_U32 ((DCAL_session_Cmd_pl_union_type_t)3U)
#define DCAL_session_Cmd_pl_String ((DCAL_session_Cmd_pl_union_type_t)4U)
#define DCAL_session_Cmd_pl_Time ((DCAL_session_Cmd_pl_union_type_t)5U)
#define DCAL_session_Cmd_pl_Filexfer ((DCAL_session_Cmd_pl_union_type_t)6U)

static inline const char *DCAL_session_Cmd_pl_type_name(DCAL_session_Cmd_pl_union_type_t type)
{
    switch (type) {
    case DCAL_session_Cmd_pl_NONE: return "NONE";
    case DCAL_session_Cmd_pl_Globals: return "Globals";
    case DCAL_session_Cmd_pl_Profile: return "Profile";
    case DCAL_session_Cmd_pl_U32: return "U32";
    case DCAL_session_Cmd_pl_String: return "String";
    case DCAL_session_Cmd_pl_Time: return "Time";
    case DCAL_session_Cmd_pl_Filexfer: return "Filexfer";
    default: return "";
    }
}


struct DCAL_session_Command_table { uint8_t unused__; };

#ifndef DCAL_session_Command_identifier
#define DCAL_session_Command_identifier flatbuffers_identifier
#endif
#define DCAL_session_Command_type_hash ((flatbuffers_thash_t)0x60a0c1fc)
#define DCAL_session_Command_type_identifier "\xfc\xc1\xa0\x60"
static inline size_t DCAL_session_Command_vec_len(DCAL_session_Command_vec_t vec)
__flatbuffers_vec_len(vec)
static inline DCAL_session_Command_table_t DCAL_session_Command_vec_at(DCAL_session_Command_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(DCAL_session_Command_table_t, vec, i, 0)
__flatbuffers_table_as_root(DCAL_session_Command)

static inline DCAL_session_Commands_enum_t DCAL_session_Command_command(DCAL_session_Command_table_t t)
__flatbuffers_scalar_field(DCAL_session_Commands, 0, 0, t)
static inline int DCAL_session_Command_command_is_present(DCAL_session_Command_table_t t)
__flatbuffers_field_present(0, t)

static inline DCAL_session_Cmd_pl_union_type_t DCAL_session_Command_cmd_pl_type(DCAL_session_Command_table_t t)
__flatbuffers_scalar_field(DCAL_session_Cmd_pl, 1, 0, t)
static inline flatbuffers_generic_table_t DCAL_session_Command_cmd_pl(DCAL_session_Command_table_t t)
__flatbuffers_table_field(flatbuffers_generic_table_t, 2, t, 0)
static inline int DCAL_session_Command_cmd_pl_is_present(DCAL_session_Command_table_t t)
__flatbuffers_field_present(1, t)


#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* DCAL_H */
